language: node_js
node_js:
- node
- '8'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
- yarn global add greenkeeper-lockfile@1
- yarn global add coveralls
- yarn global add codecov
cache: false
install:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install --ignore-scripts;
  else
    echo Normal build - frozen lockfile; yarn install --ignore-scripts --frozen-lockfile;
  fi
before_script: greenkeeper-lockfile-update
script:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install;
  else
    echo Normal build - frozen lockfile; yarn install --frozen-lockfile;
  fi
- cat ./coverage/lcov.info | coveralls
- codecov -f coverage/coverage-final.json
after_script: greenkeeper-lockfile-upload
stages:
- name: test
- name: deploy
  if: tag =~ ^v AND fork = false AND type = push
jobs:
  include:
  - stage: test
    if: type = cron
    node_js: '8'
    os: osx
    osx_image: xcode9.2
  - stage: test
    if: type = cron
    node_js: '7'
  - stage: test
    if: type = cron
    node_js: '6'
  - stage: test
    if: type = cron
    node_js: '5'
  - stage: test
    if: type = cron OR tag =~ ^v
    node_js: '4'
  - stage: deploy
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH=$HOME/.yarn/bin:$PATH
    install: []
    before_script: []
    script: yarn install --frozen-lockfile
    after_script: []
    before_deploy: yarn tidy-ci
    deploy:
      provider: npm
      email: github-external-bot@holvonix.com
      skip_cleanup: true
      api_key: "$NPM_API_KEY"
      on:
        tags: true
env:
  global:
  - secure: g9o34ZeqqxP+b5QJLvpDUx6h4uHRsrxl9BCpXZSVyBt6bCA6kvHZ7OEoA3vFKtJt1hSyK0d22zZMEKGS7e6sJCTsir+kNNiI63F9gV8BPjBw2KZBhIY3qzCs6HXHQniWISbhlaQvVDk5lNc6CojKoNj0S3AnQvClDDiAOu1GCs1TbU17JxIr9E0CyPeMW0QmlTVFIWFrRdPzB4P6N+TElyzFzjQjlojqfTfurijdDsLC9C3OyevOjRSQsvlPdcGJq2aJzW6gs/XC+CLzy+InVl351QmA9GePe8+70jns1PxzPRf7ByEpUdnEY7+WtTXlTJGzeVnrcN3k3S6Cj1NpwGHRSitCuD0rdv24s91rQGB7Ax4v3ViXn5x13T/6ZG+aM9E4FRyxRszCTMjmmMFsPEOsUyWZePDFecSOXaEFfqgl1eGYYNd4Gdw+pa+olr8F9l8cqvL+CDmPYLsVsml6tOSZs5Fw4rg32lmfG4lD5Pa4UZ0K1Tj+++oQc3wR3mTc2l/C6Ys3qpSjaRREO8E24EzPCbJ0O5d5kTrP552qf/zKrma0j4X817a2EEpg3JZUPuxBOJHyj5nz+bXe4o+S3Fd1QH7AX54SmamkAzo/gFBFucwWpKpoQhBhVdMvAI/tsq2lnRijZ1Ex7uE5lSiKAn77HjfjVYuGnQ7UhihkbT0=
  - secure: d8hh9CYplv4Pnl9AtVYfVQliH4Rb2GYLR7tRnw0iuqw3vOMDfjtXNMuA9BpQ5S/1MaWTGyl7sgPvrNDo6FwYHDyW6lSQm3k95kckA85mkFyeIskWt2ZV95bKtnsOGIKn61mDt6/8MJx3dPiIGAaGjN5PTClCaFIR51Ev12Y/vDYf1NIalu9KLO+PIEQtcQy+petkpVZzY7nNDZpyOlK8jan7jW7PEW3/wCoGDMuhmtLuz0RR+nwfx6SwwXRNrskGKJTCZ6ZVRRUi9wwTVNnur1VSJzBNSohrdZEbLFPLaJBOBmDzyV0j2Pr715a4m9sIgxlo9xBUZtFb+V35yoh423OvwSuVRXf1yhSp/SMzR6lXddfMB6Nv4MAtaFTZ1vHFma13L46HBxwVbpELBb1mTzqF6oQez6DOUDzBlv8d2L7kLjAEME5YE983fX8AeLPM9q8ShWO6VEB/IGjmz+s7wrJ3kx+P+hU8YbYaGnAsT6TdNc+823pZ6LUNnLxD6jhPo7/gviEAvOsutlusHTLIGz9dUSvF0Oirvhwv7YcuOoU73sw2Uns02csTN0kVmTrpDfdn5O1rA9KgNR7tIwkS1GKHv8ZTNL5aYRLImqEijxMr72er93r96KfYAhthjBku2LuqoR1WUqhDGehU+3Fl8vqmz3hMbxjaE+ChbdxWha0=
  - secure: Mv32tSj3qo4A6RGGofICbb2yc7PchxbrZGFKgT9UnnUcLStO4TzJ1iUgXcNq7cGGq9+tzG3206tYk75Wxf5YqgiyPozFUwxpfybLL6E328gaKU2rJZJq/Q9rRA0y1idjCMo4van5oWffDxwR+9SYvzLtMv08wnyf/+vxv0REM657VvLF0Jqdb1nGVS0ow1160SLXzS2EGf1CGqCfv3QsvexcIk8/7RTHfKIEh8GdoVTVLPbfCML+awBGxQMcJtsk6Bf0gxRIQ0JJE9dY3QRbgL1lHQ9vontU1x/H1SRyrHh/Sjg4slH7MCeKyWpi14gk5i66+wVWBILxa9yAurVwrdJ+RW34ylQfLvyKMClnT+8GQ1rJu/W25TdcSsJtjcwkcit0TZU0JNpIj51vo1sG1RJxMocKi+WRwnft+5HYS9o6ZpnCFgr2n3lwqg8Y0PdTaZqIEFoMK+C7B6un13ldNWtUvgnuPqcs64PY7rquMqR9RrubLGihfQ4LwNCQuZW9PC2oWKtWhpxadjknAu3IFPtiSfUWV4+bzdWJj4gyNb6t3L4QA/1TcQjfOfMI8/ox3Cq09VsLSj+v6jVq3nLxQxuE9cRLj3k4kZ4N2RiZTHYGkfuMjYWFYr9Z8YBx4z3B4FHjGp2GWMc36Paf+45KKc/9TP5qY1PdUYatuNCVI2M=
