language: node_js
node_js:
- node
- '8'
- '4'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
- yarn global add greenkeeper-lockfile@1
- yarn global add coveralls
- yarn global add codecov
cache: false
install:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install --ignore-scripts;
  else
    echo Normal build - frozen lockfile; yarn install --ignore-scripts --frozen-lockfile;
  fi
before_script: greenkeeper-lockfile-update
script:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install;
  else
    echo Normal build - frozen lockfile; yarn install --frozen-lockfile;
  fi
- cat ./coverage/lcov.info | coveralls
- codecov -f coverage/coverage-final.json
after_script: greenkeeper-lockfile-upload
jobs:
  include:
  - if: "(tag =~ ^v) AND (branch = master) AND (fork = false) AND (repo = holvonix-open/new-ball)"
    stage: deploy
    before_deploy: yarn tidy-ci
    deploy:
      provider: npm
      email: github-external-bot@holvonix.com
      skip_cleanup: true
      api_key: "$NPM_API_KEY"
env:
  global:
    secure: BQy9D5YWRtq+GQsqTrhEUAVZwADldhRPAHVHUw+HbdNDIJGdmmia35nzKUm41CQ7+Xvl/eHYWN+DzGI42ZlQTgDVASjlKiEj5zVLV5hyse3ibmk0EGD+ELVoy0UoNjYuo2cBIdWH97bsbwtVBs9tGriP5Rs/HZqDas/jzCAaDjmJ5DdIKmipRYJspXgPkJATM93iHyjn7rhX1c2uY79YKK/HbTFlMRaA2F5epaicpqYABqZJ4Q7njqivkXcW9wegQzOBtrpBsJUW5yvmQbCO+nvyv9WclkCQfkXwx0ss3x7HoDyEjdHIk3kmqnODg1HgfudWSaqmB4gjbPDLI6Ehvjcmb0dZg841pw2BY+oxdX6ONEPPfmvwBRO6mRDT2xADXt/Qntk6Pg7DIXcF25alVo7RIP34cyvn3+44SpWbz+A0+5URWH8+9l/sBVPyShHZdk8i42omxZXcFziU+FFRDjWKRl74Lw8C/m+WL+00fQl9nY2HY5KN/rvgqKte/gXYXHr8EcDl8XwZ6YVz5TQcqDpu9ekZY37meIhlA0CpjkSq1n3q4btCYvaXxBdBZNGePO6dARufvUUaUPlEOYhCqaO6JW91jf2YEerIVJRrHjKEDoTkGdhRpOfX4fkZsrw55dXI+9u6yrAALdwwYixg+4Lh5wUKtxim+NUmi/tWj/A=
